# 使用 airbnb 规则
extends:
  - "eslint:recommended"
  - 'eslint-config-airbnb-es5'

# 全局环境变量
env:
  es6: false
  browser: true
  node: true
  commonjs: true
  amd: true
  mocha: true

# js 语言选项
parserOptions:
  ecmaVersion: 5
  sourceType: module

# 规则, http://cn.eslint.org/docs/rules/
# 0: off 关闭规则
# 1: warn 开启规则, 使用警告级别的错误, 不会导致程序退出
# 2: error 开启规则, 使用错误级别的错误, 会导致程序退出
rules:
    # 强制一行的最大长度
    max-len: [error, 120, {
      ignoreUrls: true, # 忽略含有链接的行
      ignoreComments: true, # 忽略所有拖尾注释和行内注释
      ignoreTrailingComments: true, # 忽略拖尾注释
      ignoreStrings: true, # 忽略含有双引号或单引号字符串的行
      ignoreRegExpLiterals: true, # 忽略包含正则表达式的行
      ignoreTemplateLiterals: true, # 忽略包含模板字面量的行
    }]

    # 强制使用一致的缩进
    indent: [error, 2, {
      SwitchCase: 1 # 强制 switch 语句中的 case 子句的缩进级别 => 0: 不会缩进, 1: case 相对于 switch 缩进 2 格 (如果缩进设置为 2 个空格)
    }]

    # 强制在 switch 的冒号左右有空格
    switch-colon-spacing: [error, {
      after: false, # 禁止冒号之后有空格
      before: false # 禁止冒号之前有空格
    }]

    # 强制使用一致的反勾号、双引号或单引号
    quotes: [error, single, {
       allowTemplateLiterals: true, # 允许字符串使用反勾号
    }]

    # 禁止自身比较
    no-self-compare: [0]

    # 禁用不必要的转义字符
    no-useless-escape: [0]

    # 禁止将 undefined 作为标识符
    no-undefined: [0]

    # 禁止数字字面量中使用前导和末尾小数点
    no-floating-decimal: [0]

    # 要求或禁止使用命名的 function 表达式
    func-names: [0]
