# 使用 airbnb 规则
extends: 'eslint-config-airbnb-es5'

# 全局环境变量
# env:
#   # es6 语法
#   es6: false
#   # browser
#   browser: true
#   # node
#   node: true
#   # commonjs
#   commonjs: true
#   # amd
#   amd: true
#   # mocha
#   mocha: true

# js 语言选项
parserOptions:
  ecmaVersion: 5
  sourceType: module

# 规则, http://cn.eslint.org/docs/rules/
# 0: off 关闭规则
# 1: warn 开启规则, 使用警告级别的错误, 不会导致程序退出
# 2: error 开启规则, 使用错误级别的错误, 会导致程序退出
rules:
    # 强制一行的最大长度
    max-len:
      - 2
      - 120

    # 禁止自身比较
    no-self-compare:
      - 0

    # 禁用不必要的转义字符
    no-useless-escape:
      - 0
