sudo: false
language: node_js
node_js:
  - stable
  - 8
  - 6
  - 5

script:
  - npm run jxmTest

after_script:
  - npm run jxmCoverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  email:
    - 575099237@qq.com
